Set SensuAPIValidator timeout to 15 seconds
sensu/sensu-puppet pull request #1315
Opened 2021-11-10 23:24 UTC by robmcelhinney

Match comments and REFERENCE file.

# Pull Request Checklist

Comments in `sensu_api_validator.rb` file say and in REFERENCE.md file say that the timeout is set to 15 but it's actually set to 30.
Set it to 15 to keep it consistent.

2021-11-11 01:59 UTC, ghoneycutt commented
Would prefer to keep the default as is and instead update any documentation that is not aligned.

2021-11-11 13:22 UTC, robmcelhinney commented
> 
> 
> Would prefer to keep the default as is and instead update any documentation that is not aligned.

Ok, I changed the comments to `30` seconds then to keep it consistent.
I'll just use 15 on my config, I prefer keeping it shorter.

2021-11-15 16:15 UTC, ghoneycutt requested changes

2021-11-15 16:15 UTC, ghoneycutt commented
Thanks @robmcelhinney for finding and fixing this!

2021-11-16 21:27 UTC, merged